add masseges
dixon-che/flashcross.org pull request #4
Opened 2017-08-15 08:55 UTC by Big-d1pper

поправил форму для вывода информационных сообщений

2017-08-15 10:07 UTC, dixon-che requested changes
Делай нормальные комментарии с комитам и к пул-реквестам

2017-08-15 10:07 UTC, dixon-che commented on flashcross/settings/base_settings.py
> +FACEBOOK_APP_ID = '302058126926208'
это приватная информация, ее нужно хранить в файле local_settings, который не версионируется

2017-08-15 12:34 UTC, dixon-che commented on templates/base.html
> +                <div class="col-sm-9">
А зачем так рендерить форму? Обязательно каждый атрибут отдельно? 
Просто {{ form.username }} не сработает?

2017-08-16 10:03 UTC, Big-d1pper commented on templates/base.html
> +                <div class="col-sm-9">
так было в том темплее что ты мне дал, оно ж работает)

2017-08-16 10:03 UTC, Big-d1pper commented on flashcross/settings/base_settings.py
> +FACEBOOK_APP_ID = '302058126926208'
перенесем , там как раз есть поля пустые для етих данных, я их не замечал.

2017-08-16 11:58 UTC, dixon-che commented on templates/base.html
> +                <div class="col-sm-9">
ладно оставляй пока не переверстаешь

2017-08-16 11:58 UTC, merged